config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  get 'home/about' => 'homes#about'
  post 'home/guest' => 'homes#guest'

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :destroy]
  resources :albums
    post '/albums/login' => 'albums#login'
  resources :photos, except: [:index, :show]
  resources :comments, only: [:create, :destroy]

  namespace :admin do
    resources :users
      delete '/users' => 'users#destroy_all'
    resources :albums, except: [:new]
    resources :photos, only: [:destroy]
    resources :comments, only: [:create, :destroy]
  end

end

app/models/album.rb
class Album < ApplicationRecord

  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy


  validates :album_name, presence: true
  validates :password_digest, presence: true
  validates :user_id, presence: true

  validates :album_name, length: { maximum: 20 }
  validates :password_digest, length: { minimum: 6 }

  has_secure_password

  def Album.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    @photos = Photo.where(album_id: params[:id]).order(:image_number)
    @comment = Comment.new
    @comments = Comment.where(album_id: params[:id]).reverse_order
    respond_to do |f|
      f.html
      f.json {
        comments = Comment.joins(:user).select('comments.*, users.name').where('comments.id > ?', params[:comment][:id]).where(album_id: @album.id)
        delete_comments = Comment.only_deleted.where(album_id: @album.id)
        render json: { comments:comments, deleted_comments: delete_comments }
      }
    end
  end

  def update
    album = Album.find(params[:id])
    album.update(album_params)
    redirect_to admin_album_path(album.id)
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy
    redirect_to admin_user_path(album.user_id)
  end

  private
  def album_params
    params.require(:album).permit(:album_name, :password, :password_confirmation)
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

 before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]

  def index
  end

  def show
    @album = Album.find(params[:id])
    @photo = Photo.new
    @photos = Photo.where(album_id: params[:id]).order(:image_number)
    @comment = Comment.new
    @comments = Comment.where(album_id: params[:id]).reverse_order

    respond_to do |f|
      f.html
      f.json {
        comments = Comment.joins(:user).select('comments.*, users.name').where('comments.id > ?', params[:comment][:id]).where(album_id: @album.id)
        delete_comments = Comment.only_deleted.where(album_id: @album.id)
        render json: { comments:comments, deleted_comments: delete_comments }
      }
    end
  end

  def create
    album = Album.new(album_params)
    album.user_id = current_user.id
    if album.save
      redirect_to album_path(album.id)
      flash[:notice] = "新しいアルバムを作成しました"
    else
      redirect_back(fallback_location: user_path)
      flash[:notice] = "入力に誤りがあります"
    end
  end

  def edit
    @album = Album.find(params[:id])
    @photos = Photo.where(album_id: params[:id]).order(:image_number)
  end

  def update
    album = Album.find(params[:id])
    if album.user_id == current_user.id
      album.update(album_params)
      redirect_to edit_album_path(album.id)
      flash[:notice] = "アルバム詳細を変更しました"
    else
      redirect_to edit_album_path(album.id)
      flash[:notice] = "入力に誤りがあります"
    end
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy
    redirect_to user_path(current_user.id)
    flash[:notice] = "アルバムを削除しました"
  end



  def login
    album = Album.find_by(album_name: params[:album][:album_name], user_id: params[:album][:user_id])
    if album && album.authenticate(params[:album][:password_digest])
      #authenticate paramsで持ってきたデータと一致してるかみる
      album_log_in album
      redirect_to album
    end
  end

  def logout
  end



  private
  def album_params
    params.require(:album).permit(:album_name, :password, :password_confirmation)
  end

end

app/helpers/admin/albums_helper.rb
module Admin::AlbumsHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper

  def album_log_in(album)
    session[:album_id] = album.id
  end

  def current_album
    @current_album ||= Album.find_by(id: session[:album_id])
  end

  def album_log_out(album)
    session.delete(:album_id)
    @current_album = nil
  end

end

app/views/admin/albums/index.html.erb
<%= render 'admin/users/admin_header' %>

<div class="admin_album_index">
  <div class="admin_album_index_title">
    <%= flash[:notice] %>
    <h2>アルバム一覧</h2>
  </div>
  <div class="admin_album_list">
    <div class="admin_album_list_title">
      <li>アルバム名</li>
      <li>作成者</li>
      <li>作成日時</li>
      <li>詳細</li>
    </div>
    <% @albums.each do |album| %>
    <div class="admin_album_list_body">
        <li><%= album.album_name %></li>
        <li><% user = User.with_deleted.find(album.user_id) %><%= user.name %></li>
        <li><%= album.created_at.strftime("%Y-%m-%d %H:%M") %></li>
        <li><%= link_to "詳細", admin_album_path(album.id), class: "btn btn-default" %></li>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/albums/show.html.erb
<%= render 'admin/users/admin_header' %>

  <div class="admin_album_show">
    <div class="admin_album_show_title">
      <h2>
        <%= @album.album_name %>
        <%= link_to "アルバム削除", admin_album_path, method: :delete, class: "btn btn-danger" %>
      </h2>
    </div>

    <div class="admin_album_edit_box">
      <h3>アルバム情報の編集</h3>
      <%= form_with url: admin_album_path, model: @album do |f| %>
        <%= f.label :album_name, "アルバム名" %>
        <%= f.text_field :album_name %><br>
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation, "パスワード確認" %>
        <%= f.password_field :password_confirmation %>
        <%= f.submit "変更", class: "btn btn-success" %>
      <% end %>
    </div>

    <div class="admin_album_show_box">
      <div class="admin_album_photo">
        <div class="admin_album_photo_title">
          <li>番号</li>
          <li>写真</li>
          <li></li>
        </div>
        <% @photos.each do |photo| %>
          <div class="admin_album_photo_body">
              <li><%= photo.id %></li>
              <li><%= image_tag photo.image.url %></li>
              <li style="text-align: center;"><%= link_to "削除", admin_photo_path(photo.id), method: :delete, class: "btn btn-danger" %></li>
          </div>
        <% end %>
      </div>

      <div class="chat_box">
        <div class="chat_comment">
          <%= form_with url: admin_comments_path, model: @comment,class: "comment_form" do |f| %>
          <%= f.label :comment_text, "チャット（最大200文字）" %><br>
          <%= f.text_area :comment_text, required: true, class: "form-control" %>
          <%= f.hidden_field :album_id, value: params[:id] %>
          <%= f.hidden_field :user_id, value: current_admin.id %>
          <%= f.submit "投稿", class: "btn btn-success btn-block" %>
          <% end %>
        </div>

        <div class="comment_box">
          <div class="post_wrapper">
            <% @comments.each do |comment| %>
            <div class="comment_text" data-commentid="<%= comment.id %>">
              <% user = User.with_deleted.find(comment.user_id) %>
              <strong><%= user.name %></strong><br>
              <%= comment.comment_text %>
              <%= link_to "削除", admin_comment_path(comment.id), method: :delete %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>