config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  get 'home/about' => 'homes#about'
  post 'home/guest' => 'homes#guest'

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :destroy]
  resources :albums
    post '/albums/login' => 'albums#login'
  resources :photos, except: [:index, :show]
  resources :comments, only: [:create, :destroy]

  namespace :admin do
    resources :users
      delete '/users' => 'users#destroy_all'
    resources :albums, except: [:new]
    resources :photos, only: [:destroy]
    resources :comments, only: [:create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :album, dependent: :destroy
  has_many :photos, through: :albums
  has_many :comments

  acts_as_paranoid

  def move_to(user)
    comments.update_all(user_id: user.id)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @albums = Album.where(user_id: params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to admin_user_path(user.id)
    else
      flash[:notice] = "入力に誤りがあります"
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    user.update(email: user.deleted_at.to_i.to_s + '_' + user.email.to_s)
    redirect_to admin_users_path
    flash[:notice] = "ユーザーを削除しました"
  end

  def destroy_all
    start_time = Time.zone.local(2019, 3, 1, 00, 00, 00) #(2019年, 11月, 29日, 11時, 22分, 33秒)
    users = User.where(created_at: start_time..1.week.ago).where(guest: "true")
    users.destroy_all
    redirect_to admin_users_path
    flash[:notice] = "ユーザーを削除しました"
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def after_update_path_for(resource)
    user_path(resource.id)
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
    @user = current_user
    @album = Album.new
    @albums = @user.album
  end

  def destroy
    user = User.find(params[:id])
    user.delete
    user.update(email: user.deleted_at.to_i.to_s + '_' + user.email.to_s)
    redirect_to root_path
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_admin_header.html.erb
    <header>
      <div class="header admin_head">
      <div>
        <p><%= image_tag 'main_logo.png' %></p>
      </div>
      <nav class="head_navi">
        <li><%= link_to "登録ユーザー 一覧", admin_users_path %></li>
        <li><%= link_to "アルバム 一覧", admin_albums_path %></li>
        <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
      </nav>
      </div>
    </header>

app/views/admin/users/edit.html.erb
<%= render 'admin/users/admin_header' %>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <%= flash[:notice] %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title">ユーザー情報　編集</h2>
        </div>
        <div class="panel-body">
          <div>
          <%= form_with model: [:admin, @user] do |f| %>

            <div class="field">
              <%= f.label :name %><br />
              <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
            </div>

            <div class="field">
              <%= f.label :email %><br />
              <%= f.email_field :email, autocomplete: "email" %>
            </div>

            <div class="field">
              <%= f.label :password %> <i>(6文字以上)</i><br />
              <%= f.password_field :password, autocomplete: "new-password" %>
            </div>

            <div class="field">
              <%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
            </div>

            <div class="actions">
              <%= f.submit "Update", class: "btn btn-success" %>
            </div>
          <% end %>

          <h3>ユーザーの削除</h3>
          <%= link_to "削除", admin_user_path(@user.id), method: :delete, class: "btn btn-danger" %>
          <%= link_to "Back", :back, class: "btn btn-default" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<%= render 'admin/users/admin_header' %>

<div class="admin_user_index">
  <div class="admin_user_index_title">
    <%= flash[:notice] %>
    <h2>登録ユーザー　一覧</h2>
  </div>
  <div class="admin_user_list">
    <div class="admin_user_list_title">
      <li>id</li>
      <li>名前</li>
      <li>詳細ページ</li>
      <li>登録日時</li>
      <li><%= link_to "古いユーザーの一括削除", admin_users_path, method: :delete, class: "btn btn-danger" %></li>
    </div>
    <% @users.each do |user| %>
    <div class="admin_user_list_body">
        <li><%= user.id %></li>
        <li><%= user.name %></li>
        <li><% if user.guest == false %>
            <%= link_to "詳細", admin_user_path(user.id), class: "btn btn-default" %>
            <% end %></li>
        <li><%= user.created_at.strftime("%Y-%m-%d %H:%M") %></li>
        <li><% if user.guest == true %>
            <%= link_to "削除", admin_user_path(user.id), method: :delete, class: "btn btn-danger" %>
            <% end %></li>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<%= render 'admin/users/admin_header' %>

<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="user_show_title">
        <h2>ユーザー　詳細</h2>
      </div>
      <div class="admin_user_box">
        <nav class="user_box">
          <li>名前 |</li>
          <li>email |</li>
        </nav>
        <nav class="user_box">
          <li><%= @user.name %></li>
          <li><%= @user.email %></li>
        </nav>
        <%= link_to "ユーザー情報の編集", edit_admin_user_path(@user.id), class: "btn btn-success" %>
      </div>
      <div>
        <div class="admin_album_title"><h3>アルバム 一覧</h3></div>
        <% @albums.each do |album| %>
          <div class="admin_album_box">
            <nav class="album_box">
              <li>ID |</li>
              <li>作成 日時 |</li>
            </nav>
            <nav class="album_box">
              <li><%= album.album_name %></li>
              <li><%= album.created_at.strftime("%Y-%m-%d %H:%M") %></li>
            </nav>
            <%= link_to "アルバムの中を見る", admin_album_path(album.id), class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>