config/routes.rb
Rails.application.routes.draw do

  root 'homes#index'
  get 'home/about' => 'homes#about'
  post 'home/guest' => 'homes#guest'

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show, :edit, :destroy]
  resources :albums
    post '/albums/login' => 'albums#login'
  resources :photos, except: [:index, :show]
  resources :comments, only: [:create, :destroy]

  namespace :admin do
    resources :users
      delete '/users' => 'users#destroy_all'
    resources :albums, except: [:new]
    resources :photos, only: [:destroy]
    resources :comments, only: [:create, :destroy]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= csrf_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>

  <body>

  <% if admin_signed_in? %>
    <div class="admin_back">
      <div class="header_back"></div>
  <% else %>
    <div class="main_back">
      <div class="header_back"></div>

  <% end %>
    <%= yield %>

    <footer class="footer">
      <ul>
        <li class="footer_icon">●</li>
        <li class="footer_icon"><a href="#">サイト詳細</a></li>
        <li class="footer_icon"><a href="#">お問い合わせ</a></li>
        <li class="footer_icon">
          <% unless admin_signed_in? %>
            <%= link_to "●", new_admin_session_path %>
            <% else %>
            <%= link_to "●", destroy_admin_session_path, method: :delete %>
            <% end %>

          </li>
      </ul>
    </footer>
  </div>
  </body>
</html>